image: "$DOCKER_REGISTRY/$DOCKER_IMAGE_BUILD"

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'

variables:
  DEBUG: "false"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

before_script:
  - apt update
  - apt install -y zip

stages:
  - install
    # - test
  - build
  - deploy
  - release
#  - codeQuality

.job_common_m2_cache: &job_common_m2_cache
  cache:
    key: "${CI_PROJECT_PATH}-${CI_BUILD_REF_SLUG}"
    paths:
      - .m2/repository

job_start:
  stage: .pre
  script:
    - echo "Start the build"
    - env | sort
    - mount

job_install:
  <<: *job_common_m2_cache
  stage: install
  artifacts:
    expire_in: 1 week
    paths:
      - ./spark-*/target/*.jar
  rules:
    - if: '$CI_COMMIT_BRANCH != null'
    - if: '$CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+/'
  script:
    - ./build.sh --install

      #include:
      #  local: '.gitlab-ci-test.yml'

job_deploy_artifact:
  <<: *job_common_m2_cache
  dependencies:
    - job_install
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+/'
  retry:
    max: 2
    when: script_failure
  script:
    - ./build.sh --deploy-artifact

#job_sonar:
#  <<: *job_common_m2_cache
#  dependencies:
#    - job_install
#  stage: codeQuality
#  rules:
#    - if: '$CI_COMMIT_BRANCH == "dev"'
#  script:
#    - ./build.sh --code-quality

job_end:
  stage: .post
  script:
    - echo "End"
    - env | sort
