image: "$DOCKER_REGISTRY/$DOCKER_IMAGE_BUILD"

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'

variables:
  DEBUG: "true"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  key: "${CI_PROJECT_PATH_SLUG}-${CI_BUILD_REF_SLUG}"
  paths:
    - .m2/repository

stages:
  - install
  - test
  - build
  - deploy
  - release

.job_common_tags: &job_common_tags
  - aphp
  - cicd
  - rsareth

.job_common_m2_cache: &job_common_m2_cache
  key: "${CI_PROJECT_PATH}-${CI_JOB_NAME}-${CI_BUILD_REF_SLUG}"
  paths:
    - .m2/repository

job_start:
  image: busybox:latest
  tags: *job_common_tags
  stage: .pre
  script:
    - echo "Start the build"
    - env | sort
    - mount

job_install:
  tags: *job_common_tags
  stage: install
  cache: *job_common_m2_cache
  artifacts:
    expire_in: 1 week
    paths:
      - ./spark-*/target/*.jar
  rules:
    - if: '$CI_COMMIT_BRANCH != null'
    - if: '$CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+/'
  script:
    - ./build.sh --install
    - ./build.sh --package-artifact

include:
  local: '.gitlab-ci-test.yml'

job_deploy_artifact:
  dependencies:
    - job_install
  tags: *job_common_tags
  stage: deploy
  cache: *job_common_m2_cache
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+/'
  retry:
    max: 2
    when: script_failure
  script:
    - ./build.sh --deploy-artifact

job_end:
  tags: *job_common_tags
  stage: .post
  script:
    - echo "End"
    - env | sort
