image: "$DOCKER_REGISTRY/$DOCKER_IMAGE_BUILD"

variables:
  DEBUG: "false"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  key: "${CI_PROJECT_PATH_SLUG}"
  paths:
    - .m2/repository

stages:
  - install
  - test
  - build
  - deploy
  - release

job_start:
  image: busybox:latest
  tags:
    - aphp
    - cicd
    - rsareth
  stage: .pre
  script:
    - echo "Start the build"
    - env | sort
    - mount

.job_common_changes_condition: &job_common_changes_condition
  - .gitlab-ci*yml
  - build.sh
  - pom.xml
  - spark-*/pom.xml
  - spark-*/src/**/*

.job_common_condition_for_releasing: &job_common_condition_for_releasing
  '$CI_COMMIT_BRANCH == "master" && $CI_COMMIT_MESSAGE !~ /^\[CICD\]/'

.job_common_tags: &job_common_tags
  - aphp
  - cicd
  - rsareth

.job_common_m2_cache: &job_common_m2_cache
  key: "${CI_PROJECT_PATH}-${CI_JOB_NAME}"
  paths:
    - .m2/repository

job_install:
  tags: *job_common_tags
  stage: install
  rules:
    - changes: *job_common_changes_condition
  script:
    - ./build.sh --install

include:
  local: '.gitlab-ci-test.yml'

job_build:
  tags: *job_common_tags
  stage: build
  cache: *job_common_m2_cache
  artifacts:
    expire_in: 1 week
    paths:
      - ./spark-*/target/*.jar
  rules:
    - changes: *job_common_changes_condition
    - if: '$CI_COMMIT_BRANCH != "master"'
    - if: *job_common_condition_for_releasing
  script:
    - ./build.sh --package-artifact

job_deploy_artifact:
  dependencies:
    - job_build
  tags: *job_common_tags
  stage: deploy
  cache: *job_common_m2_cache
  rules:
    - changes: *job_common_changes_condition
    - if: '$CI_COMMIT_TAG != "" || $CI_COMMIT_BRANCH == "dev"'
  retry:
    max: 2
    when: script_failure
  script:
    - ./build.sh --deploy-artifact

job_release:
  dependencies:
    - job_build
  tags: *job_common_tags
  stage: release
  cache: *job_common_m2_cache
  rules:
    - if: *job_common_condition_for_releasing
  script:
    - ./build.sh --prepare-release

job_end:
  tags: *job_common_tags
  stage: .post
  script:
    - echo "End"
    - env | sort
