image: "$DOCKER_REGISTRY/$DOCKER_IMAGE_BUILD"

variables:
  DEBUG: "false"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - test
  - build
  - deploy
  - release

job_start:
  image: docker
  tags:
    - aphp
    - cicd
    - rsareth
  stage: .pre
  script:
    - echo "Start the build"
    - env | sort
    - mount

job_mvn-install:
  tags:
    - aphp
    - cicd
    - rsareth
  stage: .pre
  cache:
    key: "${CI_PROJECT_PATH}-${CI_JOB_NAME}"
    paths:
      - .m2/repository
  script:
    - ./build.sh --install

job_test_spark-csv:
  dependencies:
    - job_mvn-install
  tags:
    - aphp
    - cicd
    - rsareth
  stage: test
  cache:
    key: "${CI_PROJECT_PATH}-${CI_JOB_NAME}"
    paths:
      - .m2/repository
  except:
    refs:
      - master
      - tags
  artifacts:
    paths:
      - spark-csv/target/spark-csv-test-suites.zip
  script:
    - mvn -pl spark-csv test
    - cd spark-csv/target/ ; zip spark-csv-test-suites.zip surefire-reports
      
job_test_spark-dataframe:
  dependencies:
    - job_mvn-install
  tags:
    - aphp
    - cicd
    - rsareth
  stage: test
  cache:
    key: "${CI_PROJECT_PATH}-${CI_JOB_NAME}"
    paths:
      - .m2/repository
  except:
    refs:
      - master
      - tags
  artifacts:
    paths:
      - spark-dataframe/target/spark-dataframe-test-suites.zip
  script:
    - mvn -pl spark-dataframe test
    - cd spark-dataframe/target/ ; zip spark-dataframe-test-suites.zip surefire-reports

job_test_spark-hive:
  dependencies:
    - job_mvn-install
  tags:
    - aphp
    - cicd
    - rsareth
  stage: test
  cache:
    key: "${CI_PROJECT_PATH}-${CI_JOB_NAME}"
    paths:
      - .m2/repository
  except:
    refs:
      - master
      - tags
  artifacts:
    paths:
      - spark-hive/target/spark-hive-test-suites.zip
  script:
    - mvn -pl spark-hive test
    - cd spark-hive/target/ ; zip spark-hive-test-suites.zip surefire-reports

job_test_spark-meta:
  dependencies:
    - job_mvn-install
  tags:
    - aphp
    - cicd
    - rsareth
  stage: test
  cache:
    key: "${CI_PROJECT_PATH}-${CI_JOB_NAME}"
    paths:
      - .m2/repository
  except:
    refs:
      - master
      - tags
  artifacts:
    paths:
      - spark-meta/target/spark-meta-test-suites.zip
  script:
    - mvn -pl spark-meta test
    - cd spark-meta/target/ ; zip spark-meta-test-suites.zip surefire-reports

job_test_spark-postgres:
  dependencies:
    - job_mvn-install
  tags:
    - aphp
    - cicd
    - rsareth
  stage: test
  cache:
    key: "${CI_PROJECT_PATH}-${CI_JOB_NAME}"
    paths:
      - .m2/repository
  except:
    refs:
      - master
      - tags
  artifacts:
    paths:
      - spark-postgres/target/spark-postgres-test-suites.zip
  script:
    - mvn -pl spark-postgres -DskipTests test
    - cd spark-postgres/target/ ; zip spark-postgres-test-suites.zip surefire-reports

job_test_spark-quality:
  dependencies:
    - job_mvn-install
  tags:
    - aphp
    - cicd
    - rsareth
  stage: test
  cache:
    key: "${CI_PROJECT_PATH}-${CI_JOB_NAME}"
    paths:
      - .m2/repository
  except:
    refs:
      - master
      - tags
  artifacts:
    paths:
      - spark-quality/target/spark-quality-test-suites.zip
  script:
    - mvn -pl spark-quality test
    - cd spark-quality/target/ ; zip spark-quality-test-suites.zip surefire-reports

job_test_spark-query:
  dependencies:
    - job_mvn-install
  tags:
    - aphp
    - cicd
    - rsareth
  stage: test
  cache:
    key: "${CI_PROJECT_PATH}-${CI_JOB_NAME}"
    paths:
      - .m2/repository
  except:
    refs:
      - master
      - tags
  artifacts:
    paths:
      - spark-query/target/spark-query-test-suites.zip
  script:
    - mvn -pl spark-query -DskipTests test
    - cd spark-query/target/ ; zip spark-query-test-suites.zip surefire-reports

job_test_spark-sync:
  dependencies:
    - job_mvn-install
  tags:
    - aphp
    - cicd
    - rsareth
  stage: test
  cache:
    key: "${CI_PROJECT_PATH}-${CI_JOB_NAME}"
    paths:
      - .m2/repository
  except:
    refs:
      - master
      - tags
  artifacts:
    paths:
      - spark-sync/target/spark-sync-test-suites.zip
  script:
    - mvn -pl spark-sync -DskipTests test
    - cd spark-sync/target/ ; zip spark-sync-test-suites.zip surefire-reports

job_build:
  tags:
    - aphp
    - cicd
    - rsareth
  stage: build
  cache:
    key: "${CI_PROJECT_PATH}-${CI_JOB_NAME}"
    paths:
      - .m2/repository
  artifacts:
    expire_in: 1 week
    paths:
      - ./spark-{csv,dataframe,hive,meta,postgres,quality,query,sync}/target/*jar
  except:
    refs:
      - master
  script:
    - ./build.sh --package-artifact

job_deploy_artifact:
  dependencies:
    - job_build
  tags:
    - aphp
    - cicd
    - rsareth
  stage: deploy
  cache:
    key: "${CI_PROJECT_PATH}-${CI_JOB_NAME}"
    paths:
      - .m2/repository
  except:
    refs:
      - master
  retry:
    max: 2
    when: script_failure
  script:
    - ./build.sh --deploy-artifact

job_release:
  dependencies:
    - job_build
  tags:
    - aphp
    - cicd
    - rsareth
  stage: release
  cache:
    key: "${CI_PROJECT_PATH}-${CI_JOB_NAME}"
    paths:
      - .m2/repository
  only:
    refs:
      - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^\[CICD\]/
  script:
    - ./build.sh --prepare-release

job_end:
  tags:
    - aphp
    - cicd
    - rsareth
  stage: .post
  script:
    - echo "End"
    - env | sort
