jobName:    Eds Stats Calc
hostPg:     0.0.0.0
portPg:     5432
databasePg: edsr
schemaPg:   meta
userPg:     nparis
schemas:
  - dbName: pg-prod
    dbType: postgresql
    host: 0.0.0.0
    db: edsr
    user: nparis
    isActive: true
    strategy:
      extractor:
        featureExtractImplClass: io.frama.parisni.spark.meta.TestFeatureExtractImpl
  - dbName: pg-prod
    dbType: postgresql
    host: 0.0.0.0
    db: edsr
    user: nparis
    isActive: true
    strategy:
      extractor:
        featureExtractImplClass: io.frama.parisni.spark.meta.strategy.extractor.DefaultFeatureExtractImpl
  - dbName: spark-prod
    dbType: spark
    host: 0.0.0.0
    db: hive
    user: etl
    isActive: false